### PR TITLE
Feed watchdog while waiting for serial

### PR DESCRIPTION
**Pull request by xC0000005**
For STM32 systems, the option bytes may start the watchdog on power on. If we do not feed the watchdog, it will reset while waiting for serial connection. The option bytes cannot be reset without the key values used to code them, and on Malyan (and probably other boards) the users won't have them.

### CODE REVIEW

**Comment by victorpv** [comment]
How long is the hardware wathdog set for?
I am thinking the libmaple systick ISR has a hook method to hook a funtion to it, so that function gets called each timer the ISR runs, 1ms by default.
We could write a function in our HAL to hook that for certain boards that are known to have the WDT enabled from HW or from the bootloader.

I'll merge this one, but we will have to explain the need for this in the main branch and see if it's accepted, since this would affect every board.

That piece of code, waiting for !MYSERIAL, was also supposed to be different, and only wait for a number of seconds, so if the board doesn't have a serial USB connected Marlin still runs, but someone reverted it a while back by mistake.

**Comment by xC0000005** [comment]
The timer starts from max value and counts down, according to ST's hardware (I'm not sure how long it is, I think ~4 seconds based on what I'm seeing). 

BTW, stepper control is somewhat working. I say somewhat because right now I can't tell what is caused by my reverse engineered pin assignments and what is caused by the timer code.

To get some form of movement on an actual Malyan board, I tested using the Z axis port since I know 100% which pins it's attached to, and I'd tested the endstop pin to make sure it was right.
With min pulse width changed to 5 (on a whim - 1, the documented value for these drivers, did not work), I could get the Z axis to move. 

Good things:
The stepper moves, both forward and backward.
Endstop ISRs are working.

Bad things: The motors are loud - they whine, and I know whatever it is, it's related to the firmware, because I can flash back to Malyan's and they're smooth and silent.

So, progress. Steppers are good. ISRs are good. I need to figure out some more pins and get this into a real printer instead of wired up to pieces of one, but that'll have to wait until my replacement printer arrives.

**Comment by victorpv** [comment]
The watchdog has some prescaler setting, but not sure if it can be changed when it's enabled from the option bytes. 
I tested the stepper code with a logic analyzer, and the pulses when moving a single axle were 1ms long, which may be in the limit of some steppers, so increasing it to 5 seems like a good idea. I only checked 1stepper at a time. The pulses and direction were right. I did notice a few times there would be a short pause, I think it was one other interrupt, so I added code to raise the timer interrput priority,  check if it's in github (I can't right now) and if so,  raise the priority even more in case some other interrupt is going on.

**Comment by victorpv** [comment]
Meant to say the pulses were 1us long.

**Comment by xC0000005** [comment]
My tests seem to show that if the watchdog starts from option bytes, you can’t modify its operation. Right now, I’m debugging a weird problem where Marlin only advances the extruder. I have the dir pin right - my test program can move the stepper back and forth on the extruder port, but Marlin only goes forward, even if the E direction is negative.

**Comment by victorpv** [comment]
Your test program is using the same board but not marlin right?
I designed my own board, and waiting for components to arrive to solder it and give it ashot, then I'll be able to test more than with the digital analizer. I guess I could wire up a ramp board to an stm board, I think I would spend more time troubleshooting  the wiring than anything else...
Is your local code in sync with all the changes I uploaded to this fork?

**Comment by victorpv** [comment]
This line here sets the priority for the Timer ISR;
https://github.com/victorpv/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/HAL_STM32F1/HAL_timers_Stm32f1.cpp#L122

0F is the lowest adjustable priority, but i thought would still be higher than USB, I may be wrong, so you can try setting that to a lower value to see if that makes the stepper smoother.

As soon as I have my board assembled I can start to run actual print jobs.

**Comment by xC0000005** [comment]
Will do. BTW, right below there is a typo - you’re mixing up channels. STEP_TIMER_CHAN should be TEMP_TIMER_CHAN on 141. I have a reword that no longer attaches/detaches interupts, but sets the masks appropriately. If I can get my hardware working again (my workhorse printer died last night) I’ll test it.

**Comment by victorpv** [comment]
Oh thanks, I'll correct it right away. I keep 2 copies in my HDD, the working one, and one I copy the diffs to once the changes are working, so I wonder if my working copy doesn't have this typo, otherwise the stepper should not have been working...
I'll correct this one right away and compare them again once I get home.

**Comment by victorpv** [comment]
Oh I know why it was working, because I use the same channel in each time, so the channel number is just 1 in both.

**Comment by xC0000005** [comment]
When I was looking through the timer code, for some reason, I thought the numbers should be 0 based. I think they are used as an array index to function pointers for callbacks. I will check when home. And for timer enable interrupts, there’s a second call lib maple makes that is a static function inside the timer file.

**Comment by victorpv** [comment]
there is an array, but I think it somewhere subtracts 1 from the channel number, so we use 1 to 4, and that will results in indexes 0 to 3. But is good checking just to make sure, let me know if you find it's different.

**Comment by xC0000005** [comment]
Timer Attach Interupt calls:
ivoid timer_attach_interrupt(timer_dev *dev,
                            uint8 interrupt,
                            voidFuncPtr handler) {
    dev->handlers[interrupt] = handler;
    timer_enable_irq(dev, interrupt);
    enable_irq(dev, interrupt);
}

Which means that interrupt (the channel) doesn’t look like it’s subtracted.  Also you can see that enable_interupt(the additional function) is called. We use timer_enable_irq in the headers for the enable macro, but don’t call enable_irq (which can’t be called directly - it’s static. We’ll need our own copy or similar functionality).

**Comment by victorpv** [comment]
If you follow that code, the timer_enable_irq modifies the DIER register, and uses that index as the bit to enable. Bit 0 is for the update event, then bit 1 is CC1, bit 2, CC2, etc, so using the channels numbers from 1 to 4 is the right way.

I haven't had time to check the handler yet, but I am pretty sure the handler array uses index 0 for the Update event interrupt, then 1 for CC1, etc:
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/4021c32fdb809f16a61c073d04e1d8c2c487a767/STM32F3/cores/maple/libmaple/include/libmaple/timer.h#L802

The DIER register is described in page 408 of the reference manual. I think I checked all this when writing the code, but my memory is not so good so I just went and checked it again ;)

**Comment by xC0000005** [comment]
I’ll go over the manual again - there’s more tricks to the STM32 timers than I ever would have expected, and I would guess we’re not using half the functionality. Thanks for explaining.

**Comment by victorpv** [comment]
I have gone thru the timer sections a million times, and still have to go thru it again every time I work on any timer code. Definitely we are not using half the functionality, but at this point as long as the code works, I'm happy. We will get to optimize when those steppers do not whine anymore ;)

**Comment by xC0000005** [comment]
Just a note RE: steppers. After a lot of debugging the hard way, it occurred to me I'd missed a basic portion of configuration. I set the steps per unit to be correct, and the steppers operate smoothly without whining at all. Don't be like me. :) 

So: Temp control, fans, steppers, interrupts, SD card, endstops are all working for me. Next step is to install this into a functional printer and attempt to print something for real. Note - your readme says SD card wasn't working. It took me a bit to figure out for me that it's looking at 8.3 file names with an extension of .G<something> but once I did, SD card was fine (except that I had to slow it down).

**Comment by victorpv** [comment]
Glad you found the issue. I caused some issues to myself too. I spent part of my weekend trying to figure out why my custom board was reading temps in pa2 and pa3,when it sound be pa0 and pa1, found it I had reversed dual row headers, now I can't plug the mcu board and will have to run flat cables, reversing them in one end.
The good news is that in the process I started testing with an f407 mcu, and many things are working, and I modified the code to avoid HardwareTimer altogether, need to push that to the f1 version, then wire my board, but it simplifies a bit more the hardware timer stuff and will save some cycles and some ram, should be better for boards like the malyan with only 20k of ram.
Also the ChiTu board I was checking did not have read protection set, so I could read the firmware with the flash bootloader thru the serial port.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by victorpv** [comment]
I'll not merge this PR since I have merged the other change to achieve the same. Let's see if in the Marlin 2.0 discussion they agree to add this or something similar. If not, we will see to add it somewhere else in the HAL, possibly hook it to the systick ISR.

**Comment by xC0000005** [comment]
Sounds good.

**Comment by victorpv** [comment]
What do we have pending to test?
-I haven't tested attaching interrupts to the endstops, will try to test that next after I plug the board to a printer.
-Need to find out why my sd test did not work, what speed did you use?
-Steppers and ADC seem all good. 
-Timers seem good so far, we need to add code to perhaps set the timer numbers in the board config file, and do a sanity check in the HAL if HW PWM is used (I believe is not used by default, need to check)

**Comment by xC0000005** [comment]
I’m running at 1/4 speed for SD card - I’ll try upping it again, but I know it fails at full speed.
Steppers, ADC work for me. Endstop Interrupts work for me. I need to validate that not calling enable_interrupt() after timer_enable_interrupt() is ok.HardwareTimer calls both when enabling, your macros only call one, I have a chance to call both, but I admit I’m not sure what the difference is.
 
Once we select the timer numbers based on MCU, I think it is all down to sanity checks. 
I’d like to see if fastio macros really reduce program size or not, but in terms of functioning, we’re there now.

**Comment by victorpv** [comment]
I dont think the fastio Macros save much memory, may be the opposite, but I think they may save some cycles, vs using digitalWrite.
But versus using the libmaple functions, I dont think they should save much as those are marked with "inline" but I believe the compiler will not inline them if they are used often enough. With the macros we are forcing it to use those instructions rather than call the functions. We can definitely test code and speed with one option vs the other if there is no gain, we can just use the libmaple functions, should make the code more readable.

In which file in the enable_interrupt() you are referring to?
The timer code was a bit of a mess since I was changing from using the hardwareTimer class to not using it, but I have a local copy that has hardwareTimer class totally removed, and instead of attach_interrupt and detach_interrupt, that were still somewhere in the files and take more cycles, I set it now to just timer_enable_interrupt(), so the enable_interrupt may be a left over that we can remove too.

**Comment by xC0000005** [comment]
I have yet to figure out how to link to source code lines, but in timer.c, look at timer_attach_interrupt. It calls timer_enable_irq (which your macros do) and then enable_irq, a local, static function.

**Comment by victorpv** [comment]
ok I see, enable_irq() is to enable the interrupt servicing in the NVIC for a timer device, while timer_enable_irq  is to enable a particular channel (or the update event) interrupt within the timer registers.

I understand we need to call attach_interrupt initially to attach the ISR handle, and enable interrupts in both the NVIC and the timer device, then to disable and re-enable interrupts, since the handle is not changing, we can use just  timer_enable_irq and timer_disable_irq, that will enable and disable the interrupts for that timer channel.
I'll review my local code and confirm if all that is sorted out.

My latest changes were related to removing this:
https://github.com/victorpv/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/HAL_STM32F1/HAL_timers_Stm32f1.h#L99-L100

And changing all this code to not use hardwareTimer objects:
https://github.com/victorpv/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/HAL_STM32F1/HAL_timers_Stm32f1.cpp#L96-L146

PS. To link to code lines, browse to the file in github, and click in the number on the left of the line, should highlight that line, and the URL in the browser links to that highlight.
If you hold shift and click on 2 different lines, then highlights all the code in between, and the url in the browser changes to a link that highlights all that. Neat feature, I discovered it recently too.

**Comment by xC0000005** [comment]
Hey, I discovered something bad inside the validation macros this morning that I’m still working through. In essence, I was seeing macros equate to false which should not have. I finally found a note about GCC macro expansion (the documentation for the #if statement) that says non macro values are treated as zero.

So I edited my board header and commented out the enum, changing the pin definitions to #defines.
The macros started working correctly, though I won’t be home to test pin assignments until tonight.
If this is the case, anyone compiling for STM32 will need to modify their board definitions or the sanity check and feature macros may not work as intended.

Hopefull I’m wrong about how this works, but my pragma tests say otherwise.

**Comment by victorpv** [comment]
If it comes to be the only way, we can define a new board variant for the stm32duino core, that should not have much of a problem, unless changing the pins to macro breaks something else and need more changes in the core.

**Comment by victorpv** [comment]
I got a couple of successful prints yesterday with a custom board, today I hope to test the Chitu3d board.

**Comment by xC0000005** [comment]
Contgratulations! That’s a good feeling. RE the custom board - I already have a custom one for the Malyan board, just wanted you to not be like me, digging through code to figure out why the macros don’t work. If I can confirm tonight, I’ll post the the 32 bit thread to let others know.

**Comment by victorpv** [comment]
Thanks. I also had a problem with a different macro, and had to set the minimum step length value to 1 (from 0), but if I remember right you mentioned problem with the step pulse length too.
I'm not totally sure if the issue was due to the macro, or something else, need to troubleshoot it more, but the stepper code was getting stuck in a loop, and if the macros worked as they should, that loop should not have been included in the final code.
At the end anyway the stepper driver I was using needs 2uS pulses, so I had to set it to 2 to get the steppers to work reliably. I'll update the timer code now that I have tested it.

**Pull request closed without merging**
