### PR TITLE
Switch to Timer4 to avoid a hard reset on STM32F103C6 boards

### PR DESCRIPTION
**Pull request by xC0000005**
On bluepill STM32F103C6 boards, using Timer5 results in a error() vector call. Switch to 4 since these are both general purpose, 16 bit timers.

### CODE REVIEW

**Comment by victorpv** [comment]
We have to make another change, when you pointed out to this issue with the C8, I noticed I had set the same compare channel for both stepper and temp interrupts:
#define STEP_TIMER_CHAN 1
#define TEMP_TIMER_CHAN 1

We have to use a different channel in each.
We also should include a test in the Sanitycheck file to verify that none of the PWM pins use the same timer selected (beyond checking that the timer number is valid for the MCU version in question).
I'm testing  a few other changes around the timer code, then will try to think how to check and select a timer that doesn't conflict with PWM neither with the type of MCU selected, by doing some checks in Sanitycheck.

**Comment by xC0000005** [comment]
Ok. From looking at the timer cookbook, we should be using 6 & 7, which are general purpose timers with no output channel, but interrupt clocking ability. That would avoid the PWM conflicts, I think.

**Comment by victorpv** [comment]
Could be a good way. I forgot why I chose to use compare channels. I believe it was to be able to adjust the  compare channel value, while leaving the ARR unaffected But we could instead use the ARR on those 2 timers to adjust the count to the next interrupt. I have to check more on the timers, to confirm 2 things:
If the ARR can be updated on the fly (I believe it's cached, so a new value is only loaded after an update event, but there is a flag to change that behavior)
If changing the ARR resets the counter. That would be a problem since the compare values are calculated in reference to the current counter value, so if the counter value is reset to 0 when updating the ARR, then the new ARR would be off.

Another possibility is to leave ARR unchanged, and instead update the counter itself.
If you get a chance, look at using those timer. Also we should possibly skip using the HardwareTimer class and just access the libmaple functions for the timers.
But we may also leave this for later after we get other things working, since the timers at least work in the current implementation, while I haven't had the chance to test sdcard or ADC yet.

**Comment by victorpv** [comment]
In F1 Reference Manual, Figure 176. Counter timing diagram, update event when ARPE=0 (TIMx_ARR not
preloaded)
I think we should be able to just set ARPE=0 to disable the preloading stuff when we set up the timers, and adjust ARR on the fly.

**Comment by xC0000005** [comment]
That seems reasonable. From digging, I found the cause of some of my problems. According to libmaple's board definitions, C8T6 chips have only four timers (which is why moving to timer 4 worked for me).  Since I'm sure other boards are running on higher end hardware, should this be something the board defines, like EEPROM emulation?

**Comment by victorpv** [comment]
Perhaps set it in the board defines, or make the HAL automatically select one depending on the MCU?
I would think that perhaps is better to keep it out of the board defines, I dont see that kind of things going in there.
Still some of the basic timers are in all MCUs right? if so, we can just use those and leave the GEN ones free.
EDIT: They are not, timers 6 and 7 are only in high or XL density :(

I think the best is going to be to have one of the HAL files pick the timer device depending on what pins are used for PWM. Since we have plenty of timers, it's unlikely anyone will be using all timers for PWM. And if someone is using at least 1 channel from each timer for PWM, then he will get an error at compile time.

**Comment by xC0000005** [comment]
According to STM's website (http://www.st.com/en/microcontrollers/stm32f103c6.html) all the devices share timers 1-4, where 1 is apparently "advanced" and the others are general purpose.

**Comment by victorpv** [comment]
Are you using the bluepill? if so, it's a C8 MCU, double the RAM and flash of the C6, and possibly a rebadged CB with 128KB of flash. Still the same number of timers I believe, 1 to 4.

**Comment by xC0000005** [comment]
Yes. It is labeled a C6, but it definitely has 128k of ram. Malyan is shipping thousands of printers using chips labeled C6, but whose firmware is ~85kb straight from the factory. I'm using the "pull low on init" trick to get USB working in spite of the wrong resistor, and currently looking at hacking that into my maple files so I don't have to modify Marlin with the HAL_Init() function.

**Comment by victorpv** [comment]
The stm32duino core files should include the pull low trick as long as you select the board as Generic C8 or CB (not if you select Maple Mini)

**Comment by xC0000005** [comment]
Sorry - I didn't mean to add those commits (I'm having trouble mastering GIT).

**Comment by victorpv** [comment]
No problem, those are things that are needed anyway.
If I remember right the flash emulation library only supports up to 2 pages of flash, and half of it goes wasted in addresses, and the other half is for data.
So we may have to change the flash library to allow for larger space. Marlin uses up to 4KB if I remember right, so that would need 8KB total in flash to be taken from the MCU.

**Comment by victorpv** [comment]
Btw, I have had the same issues with getting multiple commits in a PR that I didn't expect. The trick is to create a new branch for each new PR you want to send, then don't add anything else in that branch, and you keep developing in the original branch, when you want to submit a new PR, create a new branch to it.
That's the easiest way I have found to deal with that, but is still cumbersome.
If all these were tested to not fail compilation, I can merge them all at once.

**Comment by xC0000005** [comment]
You'll note that I'm only using the EEPROM library for some #defines. This implementation just writes the data to the flash addresses sequentially. I'll make a new branch for the ADC when I eventually get it working in DMA mode.

**Comment by victorpv** [comment]
The only problem with that is that if done too many times it will wear down the flash.
But at the moment I guess is OK.
I have done a bunch of changes to the timers HAL to avoid using the HardwareTimer class, and have saved a few uS per cycle in the stepper ISR.
I'll see if I can merge all changes at once, yours, mine, and the changes upstream. If not, I may have to add your changes manully and close this PR.
By the way, also found a way to test if the MCU selected for compilation has a certain timer or not, there is a define within libmaple, so I will add that so the compilation fails with an error if the wrong timer is selected. Also did some more optimizations to the GPIO code to avoid some calls overhead.

**Comment by xC0000005** [comment]
Cool. I added support for the ADC in DMA mode, but right now it doesn't work with standard pin definitions  because, for instance, Marlin thinks PA0 is an "undefined" pin. For non zero pins, this works fine. Once we're using fastio macros and pin numbers as opposed to the board enums, the problems with pin numbers versus board enums will go away. I'll probably create a PR for that soon, once I'm certain there's no easy way to translate from a board pin number to a pin enum (10 for PA0, for instance).

**Comment by victorpv** [comment]
The enums are sorted per pin, but there is no straight way to translate, since some pins are not in the enum.
Steve did something for the F4, that's nice and works for the VET or ZET boards, but not for anything smaller since they dont have all the ports pins available, Some ports only a few pins.
So what he did was to set all ports consecutive in the enum, PA0-PA15-PB0-PB15 etc, then the high nibble of the number if the GPIO port, and the low nibble is the PIN in that port.
Since there are always 16 pins per port in the VET, it works, but to do that in other boards we would have  to list all pins in the enum while some would actually not be available, so we would have to add some other check to see if they are actually available.
About PA0, I thought Marlin treated -1 as undefined :( perhaps we should submit a correction to Marlin so doesn't treat 0 like that.
For GPIO the enums work fine since we can use PIN_MAP to translate from the enums to GPIO Port and GPIO Pin. Currently I can toggle the pins in about 200nS or less.

**Comment by xC0000005** [comment]
I was wrong about it treating 0 as undefined (I'm sorry). I know I saw problems with zero definition pins, but I was flat out wrong. It's >= 0.

**Comment by victorpv** [comment]
Oh that's good, then hopefully we don't have to mess much with the enums. I'll try to merge all my changes and yours today when I'm back at home so we can use that as the new base. I posted on the 2.0 bugfix thread, currently can get the stepper rate up to 60Khz without doublestepping with the changes in timers and gpio HALs, from about 55Khz or so before, seems that we are a bit faster than the re-arm, which runs at 100Mhz ;) using ADC DMA will sure help keep that CPU usage low.

**Pull request merged**
